name: Build & Upload app.zip + ASG Refresh

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: deploy

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Create app.zip
        run: |
          zip -r app.zip . \
            -x "node_modules/*" \
            -x ".git/*" \
            -x ".github/*" \
            -x ".gitignore" \
            -x "*.log"

      - name: Upload app.zip to S3
        run: |
          aws s3 cp app.zip s3://${{ secrets.AWS_S3_BUCKET }}/app.zip
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ap-northeast-1

      - name: Trigger ASG Instance Refresh
        run: |
          aws autoscaling start-instance-refresh \
            --auto-scaling-group-name mix-three-tier-asg \
            --preferences '{
              "MinHealthyPercentage": 90,
              "InstanceWarmup": 120
            }'
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ap-northeast-1
